languageCode = "zh-cn"
languageName = "简体中文"
weight = 4
title = "zzx的主页"

[params]
  displayName = "简体中文"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2006-01-02"
  logo = "/img/zzx_icon.svg"
  description = "zzx的个人主页"

[params.author]
  name = "Zixuan Zhu"
  image = "profile.jpg"
  headline = "欢迎来到zzx的主站"
  bio = "作者暂未想出bio"
  links = [
    { wechat = "/img/wechat_QR.jpg" },
    { github = "https://github.com/zzx060827" },
    { email = "mailto:zzx060827@stu.pku.edu.cn" },
  ]

