# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "主页"
  pageRef = "/"
  weight = 10

[[main]]
  name = "文章"
  pageRef = "posts"
  weight = 15

  
# “分类”本身作为父菜单，不需要链接，所以没有 url 或 pageRef
[[main]]
  name = "分类"
  weight = 20

# 下拉菜单项使用 url 指向分类页面
[[main]]
  name = "摄影"
  parent = "分类"
  url = "/categories/摄影/" # <-- 修改这里
  weight = 16

[[main]]
  name = "旅行"
  parent = "分类"
  url = "/categories/旅行/" # <-- 修改这里
  weight = 30

[[main]]
  name = "生活"
  parent = "分类"
  url = "/categories/生活/" # <-- 修改这里
  weight = 40

[[main]]
  name = "for PKUers"
  weight = 100

[[main]]
  name = "课程测评"
  parent = "for PKUers"
  url = "/reviews/"
  weight = 110

[[main]]
  name = "课程资料"
  parent = "for PKUers"
  url = "/课程资料" # <-- 修改这里
  weight = 120 


[[main]]
  name = "about me"
  pageRef = "about"
  weight = 11

[[main]]
  name = "联系我"
  weight = 100

#[[main]]
#  name = "Test"
#  pageRef = "pagTest"
#  weight = 1000


#[[main]]
#  identifier = "mastodon"
#  pre = "mastodon"
#  weight = 300
#  url = "https://masto.ai/@blowfish"



[[main]]
  parent = "联系我"
  pre = "wechat"
  url = "/img/wechat_QR.jpg"
  weight = 350


[[main]]
  parent = "联系我" 
  
  # 给它一个唯一的 identifier
  identifier = "email_contact"
  
  # 使用 "mail" 关键字来显示信封图标
  pre = "email"
  
  # 你的邮箱地址，注意前面的 "mailto:"
  url = "mailto:zzx060827@stu.pku.edu.cn"
  
  # 排序
  weight = 390

[[main]]
  identifier = "github"
  parent = "联系我"
  pre = "github"
  url = "https://github.com/zzx060827"
  weight = 400


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

 [[footer]]
   name = "标签"
   pageRef = "tags"
   weight = 10

 [[footer]]
   name = "作者"
   pageRef = "authors"
   weight = 20
